---
# Dataset maintained by the European Centre for Disease Prevention and Control (ECDC)
ECDC_CASE_DISTRIBUTION_URL: "https://opendata.ecdc.europa.eu/covid19/casedistribution/json/"
ECDC_HOSPITAL_ADMISSION_RATES_URL: "https://opendata.ecdc.europa.eu/covid19/hospitalicuadmissionrates/json/"
ECDC_COVID19_TESTING_URL: "https://opendata.ecdc.europa.eu/covid19/testing/json/"


